# Generated by Django 5.0.14 on 2026-05-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_surname",
                    models.CharField(max_length=100, verbose_name="Adı Soyadı"),
                ),
                ("age", models.IntegerField(verbose_name="Yaş")),
                ("city", models.CharField(max_length=100, verbose_name="Şehir")),
                ("profession", models.CharField(max_length=100, verbose_name="Meslek")),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="LinkedIn URL",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="GitHub URL"
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "photo_path",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/",
                        verbose_name="Profil Fotoğrafı",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncellenme"),
                ),
            ],
            options={
                "verbose_name": "Hakkımda",
                "verbose_name_plural": "Hakkımda",
                "db_table": "about_me",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("technical", "Teknik Bilgi"),
                            ("non_technical", "Teknik Olmayan Bilgi"),
                            ("research", "Araştırmalarım"),
                            ("hobby", "Hobilerim"),
                            ("book", "Okuduğum Kitaplar"),
                        ],
                        max_length=20,
                        verbose_name="Bölüm Türü",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "image_path",
                    models.ImageField(
                        blank=True, null=True, upload_to="posts/", verbose_name="Görsel"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blog_api.category",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Yazısı",
                "verbose_name_plural": "Blog Yazıları",
                "db_table": "posts",
            },
        ),
    ]
