# Generated by Django 5.0.14 on 2026-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Proje Adı")),
                ("description", models.TextField(verbose_name="Proje Açıklaması")),
                (
                    "github_url",
                    models.URLField(max_length=255, verbose_name="GitHub URL"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Yazılım Dili",
                    ),
                ),
                ("stars", models.IntegerField(default=0, verbose_name="Yıldız Sayısı")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="Proje Görseli",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Projesi",
                "verbose_name_plural": "GitHub Projeleri",
                "db_table": "projects",
            },
        ),
    ]
